proyecto/ProyectoCodo/ProyectoCodo/urls.py
from django.contrib import admin
from django.urls import path, include
from web import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('web/', include('web.urls')),
    path('api/', include('api.urls'))
]

proyecto/ProyectoCodo/api/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()

router.register(r'Alumnos', views.AlumnosViewSet, basename='alumno')
router.register(r'Entrenadores', views.EntrenadoresViewSet, basename='entrenador')

urlpatterns = [
	path('', include(router.urls)),
	path('api-auth/', include('rest_framework.urls'), name='rest_framework')
]

proyecto/ProyectoCodo/web/models.py
from django.db import models
from ProyectoCodo import settings

class Persona(models.Model):
    nombre = models.CharField(max_length=100, verbose_name='Nombre')
    apellido = models.CharField(max_length=100, verbose_name='Apellido')
    dni = models.IntegerField(unique=True, verbose_name='DNI')

    class Meta:
        abstract=True

class Alumno(Persona):

    user = models.OneToOneField(
	    settings.AUTH_USER_MODEL,
	    on_delete=models.CASCADE,
	    null=True,
	    blank=True
	    )

    def __str__(self):
        return f'{self.apellido} {self.nombre} DNI {self.dni}'

class Entrenador(Persona):
    email = models.EmailField(verbose_name='Email')

    user = models.OneToOneField(
	    settings.AUTH_USER_MODEL,
	    on_delete=models.CASCADE,
	    null=True,
	    blank=True
	)

    def __str__(self):
        return f'{self.apellido} {self.nombre}'

class Disciplina(models.Model):
    nombre = models.CharField(max_length=50, verbose_name='Disciplina o actividad')
    descripcion = models.CharField(max_length=200, verbose_name='Descripción')

    TURNOS=[
        ('mañana', 'Mañana'),
        ('tarde', 'Tarde'),
        ('noche', 'Noche'),
    ]

    turno = models.CharField(max_length=10, choices=TURNOS, verbose_name='Turno')

    def __str__(self):
        return f'{self.nombre} turno {self.turno}'

class Inscripciones(models.Model):
    DISCIPLINAS=[
        ('voley', 'Voley'),
        ('basquet', 'Básquet'),
        ('natacion', 'Natación'),
    ]

    disciplina = models.CharField(max_length=50, choices=DISCIPLINAS, verbose_name='Disciplina')

    TURNOS=[
        ('mañana', 'Mañana'),
        ('tarde', 'Tarde'),
        ('noche', 'Noche'),
    ]

    turno = models.CharField(max_length=10, choices=TURNOS, verbose_name='Turno')
    entrenador_id = models.ForeignKey(Entrenador, on_delete=models.CASCADE, null=True, blank=True)
    alumno_id = models.ManyToManyField(Alumno, null=True, blank=True)

    def __str__(self):
        return f'{self.disciplina} turno {self.turno} | Entrenador: {self.entrenador_id}'

proyecto/ProyectoCodo/web/templates/web/alta_alumno.html
{% extends 'web/base.html' %}
{% load static %}

{% block titulo %} Alta de alumno {% endblock %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'web/styles/alta_alumno.css' %}"> {% endblock %}

{% block main %}

<main>

    <form method="POST" action="{% url 'alta_alumno' %}">
        {% csrf_token %}

        <h1>Formulario de inscripción de alumno</h1>

        {{form}}

        <input type="submit" value="Enviar">
    </form>
</main>

{% endblock %}

proyecto/ProyectoCodo/web/templates/web/alta_entrenador.html
{% extends 'web/base.html' %}
{% load static %}

{% block titulo %} Alta de entrenador {% endblock %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'web/styles/alta_entrenadorr.css' %}"> {% endblock %}

{% block main %}

<main>

    <form method="POST" action="{% url 'alta_entrenador' %}">
        {% csrf_token %}

        <h1>Formulario de inscripción de entrenador</h1>
        
        {{form}}

        <input type="submit" value="Enviar">
    </form>
</main>

{% endblock %}

proyecto/ProyectoCodo/web/templates/web/alumnos.html
{% extends 'web/base.html' %}
{% load static %}

{% block titulo %} Listado de alumnos {% endblock %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'web/styles/alumnos.css' %}"> {% endblock %}

{% block main %}

<main>
    <h1>Listado de alumnos del club</h1>

    <table>

        <thead>
            <tr>
                <th>Apellido</th>
                <th>Nombre</th>
                <th>DNI</th>
            </tr>
        </thead>

        <tbody>
            {% for alumno in alumnos %}
            <tr>
                <td>{{alumno.apellido}}</td>
                <td>{{alumno.nombre}}</td>
                <td>{{alumno.dni}}</td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
</main>

{% endblock %}

proyecto/ProyectoCodo/web/templates/web/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block titulo %} {% endblock %} </title>
    
    <link rel="stylesheet" href="{% static 'web/styles/base.css' %}">

    <link rel="icon" href="{% static 'web/img/logo.png' %}" type="image/x-icon">

    {% block extra_css %} {% endblock %}
</head>

<body>
    <header>
        <img src="{% static 'web/img/logo.png' %}" alt="Logo del club">
        <h1>Club Social y Deportivo LAXUS</h1>
        <img src="{% static 'web/img/logo.png' %}" alt="Logo del club">
        <div class="acciones">
            {% if not user.is_authenticated %} <a class="login" href="{% url 'login' %}"> Iniciar sesión </a> {% endif %}
            
            {% if user.is_authenticated %} <a class="logout" href="{% url 'logout' %}"> Cerrar sesión </a> {% endif %}
        </div>
    </header>

    <nav>
        <ul>
            <li><a href="{% url 'index' %}">Inicio</a></li>
            {% if perms.web.view_alumno %} <li><a href="{% url 'alumnos' %}">Alumnos</a></li> {% endif %}
            {% if perms.web.add_alumno %} <li><a href="{% url 'alta_alumno' %}">Alta alumno</a></li> {% endif %}
            {% if perms.web.add_entrenador %} <li><a href="{% url 'alta_entrenador' %}">Alta Entrenador</a></li> {% endif %}
            {% if perms.web.view_disciplina %} <li><a href="{% url 'disciplinas' %}">Disciplinas y actividades</a></li> {% endif %}
            {% if perms.web.add_inscripcion %} <li><a href="{% url 'inscripcion' %}">Inscripciones</a></li> {% endif %}
        </ul>
    </nav>


    <section>
        {% if messages %}
        <div class="messages">

            {% for message in messages %}
            <h3 {% if message.tags %} class="{{message.tags}}" {% endif %}">{{message}}</h3>
            {% endfor %}

        </div>
        {% endif %}
    </section>

    {% block main %} {% endblock %}

    <footer>

            <div class="contacto">
                <h3>Contacto</h3>
                <p>Dirección: Av. De los Lagos 19, Nordelta</p>
                <p>Email: clublaxus@gmail.com</p>
                <p>Teléfono: 1123456789</p>
            </div>

            <div class="redes">
                <h3>Seguinos en redes</h3>
                <a href="https://facebook.com/guidodiz" target="_blank"><img src="{% static 'web/img/fb.png' %}"
                        alt="Facebook"></a>
                <a href="https://instagram.com/_guidodiz" target="_blank"><img src="{% static 'web/img/ig.png' %}"
                        alt="Instagram"></a>
                <a href="https://twitter.com" target="_blank"><img src="{% static 'web/img/tw.png' %}"
                        alt="Twitter"></a>
            </div>

            <div class="derechos">
                <h4>&copy; 2024 Club Social y Deportivo Laxus. Todos los derechos reservados.</h4>
            </div>

    </footer>
</body>

</html>

proyecto/ProyectoCodo/web/templates/web/disciplinas.html
{% extends 'web/base.html' %}
{% load static %}

{% block titulo %} Disciplinas {% endblock %}
{% block extra_css %} <link rel="stylesheet" href="{% static 'web/styles/disciplinas.css' %}"> {% endblock %}

{% block main %}

<main>
    <h1>Lista de actividades deportivas</h1>

    <table>

        <thead>
            <tr>
                <th>Disciplina</th>
                <th>Turno</th>
            </tr>
        </thead>

        <tbody>
            {% for disciplina in disciplinas %}
            <tr>
                <td>{{disciplina.nombre}}</td>
                <td>{{disciplina.turno}}</td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
</main>

{% endblock %}

proyecto/ProyectoCodo/web/templates/web/entrenador.html
{% extends 'web/base.html' %}
{% load static %}

{% block titulo %} Perfil de entrenador {% endblock %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'web/styles/perfil_entrenador.css'%}"> {% endblock %}

{% block main %}

<main>
    <h1>¡Bienvenido {{nombre | upper}}!</h1>

    <h2>Lista de cursos</h2>

    <table>

        <thead>
            <tr>
                <th>Curso</th>
                <th>Turno</th>
            </tr>
        </thead>

        <tbody>
            {% for key, info_curso in cursos.items %}
            <tr>
                <td>{{ info_curso.disciplina }}</td>
                <td>{{ info_curso.turno }}</td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
</main>

{% endblock %}

proyecto/ProyectoCodo/web/templates/web/index.html
{% extends 'web/base.html' %}
{% load static %}

{% block titulo %} Inicio {% endblock %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'web/styles/index.css' %}"> {% endblock %}

{% block main %}

<main>
    <p>El Club Social y Deportivo Laxus es un vibrante centro comunitario que ofrece una amplia gama de actividades para
        personas de todas las edades. Situado en el corazón del barrio, nuestro club es un lugar acogedor donde los
        residentes pueden reunirse, socializar y participar en emocionantes deportes y actividades recreativas.</p>

    <p>Nuestra instalación cuenta con excelentes instalaciones para voley, básquet y natación, lo que brinda a nuestros
        miembros la oportunidad de mantenerse activos y saludables mientras disfrutan de su tiempo libre.</p>

    <p>Además de nuestras actividades deportivas, también organizamos eventos sociales y culturales que fomentan la
        camaradería y el espíritu comunitario. Desde barbacoas familiares hasta noches de cine al aire libre, siempre
        hay algo emocionante sucediendo en nuestro club.</p>

    <p>¡Unite a nosotros en el Club Social y Deportivo Laxus y sé parte de una comunidad activa y unida!</p>
</main>

{% endblock %}

proyecto/ProyectoCodo/web/templates/web/inscripcion.html
{% extends 'web/base.html' %}
{% load static %}

{% block titulo %} Inscripcion {% endblock %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'web/styles/inscripcion.css' %}"> {% endblock %}

{% block main %}

<main>

    <form method="POST" action="{% url 'inscripcion' %}">
        {% csrf_token %}

        <h1>Inscripción a las actividades</h1>

        {{form}}

        <input type="submit" value="Enviar">
    </form>
</main>

{% endblock %}

proyecto/ProyectoCodo/web/templates/web/inscripciones.html
{% extends 'web/base.html' %}
{% load static %}

{% block titulo %} Inscripciones {% endblock %} 
{% block extra_css %} <link rel="stylesheet" href=""> {% endblock %}

{% block main %} 

<h1>Formulario de inscripción</h1>

<form method="POST" action="{% url 'inscripciones' %}">
    {% csrf_token %}
    
    {{form}}

    <input type="submit" value="Enviar">
</form>

{% endblock %}

proyecto/ProyectoCodo/web/templates/web/profile.html
{% extends 'web/base.html' %}

{% block titulo %} Profile {% endblock %} 
{% block extra_css %} <link rel="stylesheet" href=""> {% endblock %}
{% block main %} 

<h1>¡Bienvenid@ {{nombre}}!</h1>

{% endblock %}

proyecto/ProyectoCodo/web/templates/web/rent.html
{% extends 'web/base.html' %}

{% block titulo %} Alquiler de libros {% endblock %} 
{% block extra_css %} <link rel="stylesheet" href=""> {% endblock %}
{% block main %} 

<h1>Alquiler de libros</h1>

<form method="POST" action="{% url 'rent' %}">
    {% csrf_token %}
    
    {{form}}

    <input type="submit" value="Enviar">
</form>

{% endblock %}